// <auto-generated />
using System;
using System.Collections.Generic;
using Blog.Services.Blogging.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blog.Services.Blogging.API.Migrations
{
    [DbContext(typeof(BloggingDbContext))]
    [Migration("20220213001529_Translations as value object")]
    partial class Translationsasvalueobject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<int>("Comments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comments_count");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("HeaderImgUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("header_img_url");

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("likes_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("views_count");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_posts_category");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Category"), "hash");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_posts_created_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CreatedAt"), "btree");
                    NpgsqlIndexBuilderExtensions.HasSortOrder(b.HasIndex("CreatedAt"), new[] { SortOrder.Descending });

                    b.HasIndex("Likes")
                        .HasDatabaseName("ix_posts_likes_count");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Likes"), "btree");

                    b.HasIndex("Views")
                        .HasDatabaseName("ix_posts_views_count");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Views"), "btree");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_posts_status_created_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Status", "CreatedAt"), "btree");
                    NpgsqlIndexBuilderExtensions.HasSortOrder(b.HasIndex("Status", "CreatedAt"), new[] { SortOrder.Descending });

                    b.ToTable("posts", "blogging");

                    b.HasDiscriminator<string>("type").HasValue("PostBase");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostTranslationBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("language");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("title");

                    b.Property<string>("translation_type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("translation_type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_post_translations");

                    b.HasIndex("PostId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_post_translations_post_id_language");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PostId", "Language"), "btree");

                    b.HasIndex("Title", "Description", "Content")
                        .HasDatabaseName("ix_post_translations_base_english")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    b.ToTable("post_translations", "blogging");

                    b.HasDiscriminator<string>("translation_type").HasValue("PostTranslationBase");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.TagAggregate.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("language");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("value");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_tags_value");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Value"), "btree");

                    b.HasIndex("Language", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_language_value");

                    b.ToTable("tags", "blogging");
                });

            modelBuilder.Entity("post_translations_tags", b =>
                {
                    b.Property<Guid>("post_translation_id")
                        .HasColumnType("uuid")
                        .HasColumnName("post_translation_id");

                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("post_translation_id", "tag_id")
                        .HasName("pk_post_translations_tags");

                    b.HasIndex("tag_id")
                        .HasDatabaseName("ix_post_translations_tags_tag_id");

                    b.ToTable("post_translations_tags", "blogging");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.LifestylePost", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase");

                    b.HasDiscriminator().HasValue("lifestyle");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.LifestylePostTranslation", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostTranslationBase");

                    b.HasDiscriminator().HasValue("lifestyle");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RecipePost", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recipe_difficulty");

                    b.Property<string>("FoodComposition")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recipe_food_composition");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recipe_meal");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_servings_count");

                    b.Property<string>("SongUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("recipe_song_url");

                    b.Property<List<string>>("_preparationMethods")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipe_preparation_methods");

                    b.Property<List<string>>("_tastes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipe_tastes");

                    b.HasDiscriminator().HasValue("recipe");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RecipePostTranslation", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostTranslationBase");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recipe_cuisine");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recipe_dish_name");

                    b.Property<List<string>>("_ingredients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipe_ingredients");

                    b.HasIndex("Title", "Description", "Content", "Cuisine", "DishName")
                        .HasDatabaseName("ix_post_translations_recipe_english")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    b.HasDiscriminator().HasValue("recipe");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ReviewPostBase", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("review_rating");

                    b.Property<string>("ReviewItemType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("review_item_type");

                    b.HasDiscriminator().HasValue("ReviewPostBase");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ReviewPostTranslationBase", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostTranslationBase");

                    b.HasDiscriminator().HasValue("ReviewPostTranslationBase");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ProductReviewPost", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ReviewPostBase");

                    b.HasDiscriminator().HasValue("productreview");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ProductReviewPostTranslation", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ReviewPostTranslationBase");

                    b.HasDiscriminator().HasValue("productreview");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RestaurantReviewPost", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ReviewPostBase");

                    b.HasDiscriminator().HasValue("restaurantreview");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RestaurantReviewPostTranslation", b =>
                {
                    b.HasBaseType("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ReviewPostTranslationBase");

                    b.Property<List<string>>("_restaurantCuisines")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("review_restaurant_cuisines");

                    b.HasDiscriminator().HasValue("restaurantreview");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase", b =>
                {
                    b.OwnsOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.User", "Author", b1 =>
                        {
                            b1.Property<Guid>("PostBaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("author_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("author_name");

                            b1.HasKey("PostBaseId");

                            b1.HasIndex("Id")
                                .HasDatabaseName("ix_posts_author_id");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Id"), "hash");

                            b1.ToTable("posts", "blogging");

                            b1.WithOwner()
                                .HasForeignKey("PostBaseId")
                                .HasConstraintName("fk_posts_posts_id");
                        });

                    b.OwnsOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.User", "Editor", b1 =>
                        {
                            b1.Property<Guid>("PostBaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("editor_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("editor_name");

                            b1.HasKey("PostBaseId");

                            b1.ToTable("posts", "blogging");

                            b1.WithOwner()
                                .HasForeignKey("PostBaseId")
                                .HasConstraintName("fk_posts_posts_id");
                        });

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostTranslationBase", b =>
                {
                    b.HasOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase", null)
                        .WithMany("Translations")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_translations_posts_post_id");
                });

            modelBuilder.Entity("post_translations_tags", b =>
                {
                    b.HasOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostTranslationBase", null)
                        .WithMany()
                        .HasForeignKey("post_translation_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_post_translations_tags_post_translations_post_translation_id");

                    b.HasOne("Blog.Services.Blogging.Domain.AggregatesModel.TagAggregate.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_post_translations_tags_tags_tag_id");
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RecipePost", b =>
                {
                    b.OwnsOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RecipeTime", "Time", b1 =>
                        {
                            b1.Property<Guid>("RecipePostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("CookingTime")
                                .HasColumnType("integer")
                                .HasColumnName("recipe_cooking_minutes");

                            b1.Property<int>("PreparationTime")
                                .HasColumnType("integer")
                                .HasColumnName("recipe_preparation_minutes");

                            b1.Property<uint>("xmin")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.HasKey("RecipePostId");

                            b1.ToTable("posts", "blogging");

                            b1.WithOwner()
                                .HasForeignKey("RecipePostId")
                                .HasConstraintName("fk_posts_posts_id");
                        });

                    b.Navigation("Time")
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.ProductReviewPost", b =>
                {
                    b.OwnsOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.Product", "Product", b1 =>
                        {
                            b1.Property<Guid>("ProductReviewPostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("varchar(60)")
                                .HasColumnName("review_item_name");

                            b1.Property<string>("WebsiteUrl")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("review_item_website_url");

                            b1.Property<uint>("xmin")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.HasKey("ProductReviewPostId");

                            b1.ToTable("posts", "blogging");

                            b1.WithOwner()
                                .HasForeignKey("ProductReviewPostId")
                                .HasConstraintName("fk_posts_posts_id");
                        });

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RestaurantReviewPost", b =>
                {
                    b.OwnsOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.Restaurant", "Restaurant", b1 =>
                        {
                            b1.Property<Guid>("RestaurantReviewPostId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("varchar(60)")
                                .HasColumnName("review_item_name");

                            b1.Property<string>("WebsiteUrl")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("review_item_website_url");

                            b1.Property<uint>("xmin")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.HasKey("RestaurantReviewPostId");

                            b1.ToTable("posts", "blogging");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantReviewPostId")
                                .HasConstraintName("fk_posts_posts_id");
                        });

                    b.Navigation("Restaurant")
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.RestaurantReviewPostTranslation", b =>
                {
                    b.OwnsOne("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.Address", "RestaurantAddress", b1 =>
                        {
                            b1.Property<Guid>("RestaurantReviewPostTranslationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("review_restaurant_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("review_restaurant_country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("review_restaurant_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("varchar(10)")
                                .HasColumnName("review_restaurant_zipcode");

                            b1.Property<uint>("xmin")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.HasKey("RestaurantReviewPostTranslationId");

                            b1.ToTable("post_translations", "blogging");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantReviewPostTranslationId")
                                .HasConstraintName("fk_post_translations_post_translations_id");
                        });

                    b.Navigation("RestaurantAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Services.Blogging.Domain.AggregatesModel.PostAggregate.PostBase", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
